version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/workspace
      - ./db:/var/lib/mysql
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
