version: '3'

services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017
    volumes:
      - ./:/workspace

  mongo:
    container_name: mongo
    image: mongo:5.0.6-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=sample
      - TZ=Asia/Tokyo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
